[package]
name = "mqtt-controller-client"
version = "0.1.1"
authors = ["Julian Ulrich <j.ulrich@tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
paho-mqtt = "0.6.0"